import type { Metadata } from "next";
import "../styles/globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";

export const metadata: Metadata = {
  title: "Welcome | NextJs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="scroll-smooth focus:scroll-smooth" lang="en">
      <head>
        <link rel="icon" href="./images/webicon/blogs.ico" />
      </head>
      <body className="bg-[#f0f2f5]">
        <AntdRegistry>{children}</AntdRegistry>
      </body>
    </html>
  );
}
